### ISSUE TITLE
Import schools in Peru

### ISSUE THREAD

**Issue by dannykath** [developmentseed/mapping#10]
Last year data team  started import  schools  in Peru, @rub21  created the task and structure for this process.
The process of importing buildings is  very important  because currently in Peru although the data of schools is open data,  it is just available in [MINEDU](http://sigmed.minedu.gob.pe/mapaeducativo/) site.
This the reason why the team decided import of schools in Peru , and is a good way for create ties around the community. 
We are going continue the process of import  schools in Peru .
 
 #### Task Manager 
https://osm-pe.github.io/schools-import/#5/-8.744/-75.927
 #### Mapping sources 
 - Data of Ministery of Education
 - Bing Satellite Imagery
 #### Coverage
  - Peru
 #### Activities
 The guide is available here : 
 https://wiki.openstreetmap.org/wiki/Import/Catalogue/Peru/schools
 #### Status
![status](https://user-images.githubusercontent.com/8483644/35513563-83d37a28-04d1-11e8-9e9b-bfb3a1137579.png)
Just completed Ayacucho, the most of part in Junin and Lima.
 
 cc. @olafveerman @Rub21 @developmentseed/data-team

**Comment by dannykath** [comment]
### Progress 01/29/2018 - 02/02/2018
Great work team!!! :tada:  :tada:  
In this week  we were working 2 hours each day.
We were imported 2  kinds of schools around of Peru in this week.:
* 2257 ```amenity=school``` 
* 1175 ``` amenity= kindergarten ```  
You can get the all the import data using this [query](http://overpass-turbo.eu/s/vPr)

![data](https://user-images.githubusercontent.com/8483644/35784112-65408c1c-09e1-11e8-827e-8312ccb91f56.png)

cc @olafveerman  @developmentseed/all

**Comment by dannykath** [comment]
In this week we imported **4,238** schools in Peru 
### Progress  03/19/2018 - 03/23/2018

User | Schools
---|---
calfarome |644
dannykath|1,530
ediyes| 554
karitotp| 746
RichRico | 82
piligab | 682
**Total**|**4,238**

**Comment by Geoyi** [comment]
This is awesome 🎉, thanks for great work and updating @dannykath. I am tagging myself here and would love to see more progress. It might be super helpful to [our school mapping project](https://github.com/developmentseed/ds-business/issues/657).

**Comment by dannykath** [comment]
no more actions here!
