### ISSUE TITLE
HOT mapping + validation: Flood Affected Communities in Bangladesh (Panchagarh, Rangpur)

### ISSUE THREAD

**Issue by piligab** [developmentseed/mapping#12]
The Forecast-based Financing (FbF) project in Bangladesh intends to support the vulnerable people of Panchagarj district exposed to Cyclones. Recently due to cyclone induced inundation and strong winds, communities in Panchagarj have been supported with a cash transfer programme. This early action was activated based on forecast information, in order to support families in a timely manner to conduct mitigation and preparedness actions to minimize risks due to their vulnerability and exposure to cyclones. Exposure data is still a challenge, as existing maps do not show clearly show where the households are located, therefore having a OSM map of the existing communities, will help us to analyze the extend of the affectation for evaluation purposes, but will also help us to upgrade the FbF mechanism for future potential activations, this will allow us to prioritize in a more effective way the most exposed and vulnerable households.

Development Seed data team as part of the HOT community is taking part of this disaster mapping efforts, We are going to validate the buildings and highways as the task describe!

### Tasking Manager 
- [x] https://tasks.hotosm.org/project/3630

### Mapping sources
- Bing 
- JOSM 

#### Task Coverage 
- Bangladesh (Panchagarh, Rangpur)

#### Activities
- Go through the instructions before you start. 
- Valid all the buildings, roads and waterways in the task.

#### - Task #3630
![image](https://user-images.githubusercontent.com/19536044/35575532-9cefbe52-05aa-11e8-89fa-3ddf069cface.png)

- Right now, the task is 71% mapped and 21% validated. So let's map and valid in the priority area all the buildings, roads and waterways at 100%.
![image](https://user-images.githubusercontent.com/19536044/35575570-b24670b6-05aa-11e8-9ef9-cf6a85cb4e5d.png)

If you have any comment or suggestion please post on this ticket!

cc. @olafveerman @Rub21 @developmentseed/data-team

**Comment by RichRico** [comment]
Thank you everyone :clap: who worked on this task!

We finish the mapping and validation in the priority area


![image](https://user-images.githubusercontent.com/8484029/41684520-3de4a1b2-74a3-11e8-94a4-802158099805.png)
