### ISSUE TITLE
In response to OpenStreetMap redaction in Peru / En respuesta a la redacción de OpenStreetMap en Perú

### ISSUE THREAD

**Issue by piligab** [developmentseed/mapping#13]
## ENGLISH VERSION 
The [DWG](https://wiki.openstreetmap.org/wiki/Data_working_group) has received a notification of [copyright infringement](http://dmca.openstreetmap.org/), alleging that some data has been copied to OpenStreetMap, affecting Peru.

6 or 7 years ago, the user [TELECOM IP](https://www.openstreetmap.org/user/TELCOM%20IP) made an import of private data, those imports was made in around 28 cities of Peru. [TELECOM IP](https://www.openstreetmap.org/user/TELCOM%20IP) could not verify the [origin and the license of the data](https://www.openstreetmap.org/changeset/7218867), so the company Guiacalles that registered the claim, showed that the data came from them (using, among other methods, some streets of the trap https://es.wikipedia.org/wiki/Calle_trampa).

The imported OSM data were analyzed and verified by DWG and they decided to do the redaction - https://www.openstreetmap.org/redactions/101, which should finish in 2 weeks. So far  there are [many places affected.](https://osmcha.mapbox.com/changesets/55895426?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%2C%22value%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22Redact%22%2C%22value%22%3A%22Redact%22%7D%5D%7D)

<img width="1186" alt="screen shot 2018-01-30 at 6 07 41 pm" src="https://user-images.githubusercontent.com/1152236/35596609-93a4eb36-05e8-11e8-8822-ff1c82ee0a5a.png">

- https://www.openstreetmap.org/edit#map=17/-12.05974/-75.22721 
- https://www.openstreetmap.org/edit#map=17/-16.39974/-71.54168

**The OSM Peru community is waiting until the redaction finished to start repairing all the affected places.So far there are starting some actions.**

- [ ] Creations of  task with the areas affected (according to [naoliv](https://www.openstreetmap.org/user/naoliv)).

We are going to report on this ticket every next actions to start the fix affected places, join us to [Telegram](https://web.telegram.org/#/im?p=@osmPe) to make the coordination of the efforts. :muscle: 

*If you have any comment or suggestion please post on this ticket!* :rocket: 

## SPANISH VERSION 
La [DWG](https://wiki.openstreetmap.org/wiki/Data_working_group) ha recibido una notificación de infracción de derechos de autor (a través de http://dmca.openstreetmap.org/), alegando que algunos datos se han copiado a OpenStreetMap, afectando al Perú.

Hace 6 o 7 años, el usuario [TELECOM IP](https://www.openstreetmap.org/user/TELCOM%20IP) realizó una importación de datos privados, esas importaciones se realizaron en alrededor de 28 ciudades del Perú. [TELECOM IP](https://www.openstreetmap.org/user/TELCOM%20IP) no pudo verificar el [origen y la licencia de los datos] (https://www.openstreetmap.org/changeset/7218867), es así que la empresa Guiacalles, quien registró el reclamo, mostró que los datos provenían de ellos (utilizando, entre otros métodos, algunas calles de la trampa https://es.wikipedia.org/wiki/Calle_trampa).

Los datos importados de OSM fueron analizados y verificados por DWG y decidieron hacer la redacción - https://www.openstreetmap.org/redactions/101, que debería finalizar en 2 semanas. Hasta ahora hay [muchos lugares afectados.](https://osmcha.mapbox.com/changesets/55895426?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%2C%22value%22%3A%22-87.5804%2C-18.5259%2C-68.5073%2C0.2157%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22Redact%22%2C%22value%22%3A%22Redact%22%7D%5D%7D)

<img width="1186" alt="screen shot 2018-01-30 at 6 07 41 pm" src="https://user-images.githubusercontent.com/1152236/35596609-93a4eb36-05e8-11e8-8822-ff1c82ee0a5a.png">

- https://www.openstreetmap.org/edit#map=17/-12.05974/-75.22721 
- https://www.openstreetmap.org/edit#map=17/-16.39974/-71.54168

**La comunidad de OSM Perú está esperando hasta que la redacción finalice para comenzar a reparar todos los lugares afectados. Hasta ahora están comenzando algunas acciones.**

- [ ] Crear una tarea con las áreas afectadas (de acuerdo a [naoliv](https://www.openstreetmap.org/user/naoliv)) 

Vamos a informar en este ticket sobre las siguientes acciones para iniciar la reparación de los lugares afectados, únete a [Telegram](https://web.telegram.org//im?p=@osmPe) para hacer la coordinación de los esfuerzos. :muscle: 

*Si tiene algún comentario o sugerencia, por favor publique un comentario en este ticket!.* :rocket: 

cc. @olafveerman @Rub21 @naoliv @johnarupire @ovruni @yachaqruna @developmentseed/data-team

**Comment by piligab** [comment]
:wave: hi everyone, @Rub21 created a new repository on osm-pe, all things about this redaction we will see in this repository :point_right: https://github.com/osm-pe/osm-peru-redaction. :nerd_face: 

No more actions here! :rocket:

**Comment by Rub21** [comment]
let's do the coordination in this repo/tickets https://github.com/osm-pe/osm-peru-redaction/issues/1
