### ISSUE TITLE
HOT mapping and validation: Beledweyne, Somalia - 2018 Flood Crisis Project 02

### ISSUE THREAD

**Issue by RichRico** [developmentseed/mapping#23]
Forecast (until 8 May) includes heavy rains (50-250mm) with high risk of flooding in Shabelle and Juba basins, mainly in Hiraan region and in lower reaches of Shabelle River (SWALIM, 02/05/2018; SWALIM, 30/04/2018; OCHA, 26/04/2018). Flash floods will likely cause further displacement along the Shabelle riverbanks and in other flood-prone areas. AWD/Cholera and other waterborne diseases are likely to spread and there is risk of a new cholera outbreak.

Beledweyne district (Hiraan region) has been particularly affected, with 150,000 people displaced in Beledweyne town. Middle and Lower Shabelle, Bay, Jubaland, Galgaduud, and Banaadir regions have also been affected. In Bay, Banaadir, and Galgaduud regions flash flooding has affected IDP settlements, worsening the already vulnerable conditions of IDPs. Urgent needs include WASH, health, shelter, and food. There are concerns that the severe flooding will trigger a cholera outbreak.

Development Seed data team as part of the HOT community is taking part of this disaster mapping efforts, We are going to mapping and validate the buildings as the task describe!

### Tasking Manager

- [x] https://tasks.hotosm.org/project/4491

### Mapping sources

- JOSM
- TMS imagery :point_down: ```https://{switch:services,server}.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}?blankTile=false```

### Task Coverage

- Beledweyne

### Activities

- Go through the instructions before you start.

- Map and valid all the buildings in the task.

### Tasks status

- Task #4491

![image](https://user-images.githubusercontent.com/8484029/39711823-86016028-51e6-11e8-8f20-0984de378270.png)

- Right now, the task is 83% mapped and 62% validated. So let's map and valid all the buildings at 100%.

![image](https://user-images.githubusercontent.com/8484029/39711884-b85f03d6-51e6-11e8-9264-4651f34977ab.png)

If you have any comment or suggestion please post on this ticket!

cc. @olafveerman @Rub21 @developmentseed/data-team

**Comment by piligab** [comment]
Good work everyone who worked on complete this task to :100:% 
![image](https://user-images.githubusercontent.com/19536044/39761763-8d1d22f8-529e-11e8-97e8-4c81ea1902ff.png)
