### ISSUE TITLE
HOT mapping and validation: In response Peru earthquake - Incuyo 

### ISSUE THREAD

**Issue by karitotp** [developmentseed/mapping#4]
On Sunday 14 January 2018, an earthquake of magnitude 7.1 M affected the department of Arequipa in Peru, cracking building facades and scattering rubble on streets. Its epicenter was in the sea, 56 kilometers from the Arequipa town of Lomas.

Development Seed data team as part of the HOT community is taking part of this disaster mapping efforts, We are going to map and validate the buildings and highways as the task describe!

### Tasking Manager 
- [ ] https://tasks.hotosm.org/project/4024

### Mapping sources
- Bing imagery, DigitalGlobe Premium 
- JOSM

#### Task Coverage 
- Incuyo, Peru Area

#### Activities
- Go through the instructions before you start. 
- Map and valid all the roads and buildings in the task.

#### - Task #4024
![screenshot from 2018-01-15 09-35-11](https://user-images.githubusercontent.com/11504548/34947194-6a3844fe-f9d7-11e7-8c73-eb8274237fb5.png)

- Right now, the task is 40% mapped and 0% validated. So let's map and valid all the roads and buildings at 100%. 

![screenshot from 2018-01-15 09-35-47](https://user-images.githubusercontent.com/11504548/34947215-7d8c2052-f9d7-11e7-8c29-0851ca9c59ef.png)

if you have any comment or suggestion please post on this ticket!

cc. @olafveerman @Rub21 @developmentseed/data-team

**Comment by piligab** [comment]
:clap: Good work data team and community.
![image](https://user-images.githubusercontent.com/19536044/35224990-01f79db2-ff55-11e7-82d6-f3b5e558f1b0.png)

### We mapped at :100: % and validated at 72%
![image](https://user-images.githubusercontent.com/19536044/35225003-1256bc9c-ff55-11e7-99e9-79281135f9c5.png)

**Comment by piligab** [comment]
We finished this task to 100%
![image](https://user-images.githubusercontent.com/19536044/35462706-1278a884-02bb-11e8-8683-63f88e299da9.png)
