### ISSUE TITLE
Mapping buildings and roads in Special Economics Zones

### ISSUE THREAD

**Issue by karitotp** [developmentseed/mapping#44]
DevelopmentSeed data team is mapping [Special Economics Zones](https://en.wikipedia.org/wiki/Special_economic_zone) around the world, the features that will be mapped in OSM are `buildings` and `roads` within the boundaries of these economic zones. To tracing these features we are going to use the most appropriate satellite imageries available according to each area in which we work.

## Mapping sources for tracing

- Satellite Imagery:
  - DG Standard 
  - DG Premium
  - Esri World Imagery 
  - Bing

## Changeset Comment

   - `Mapping builidngs and roads in SEZ`

## Questions?

If you have questions or comments, please lets us know.

**Comment by ridixcr** [comment]
Some existing buildings do not appear with any  satellite  image(DG Standard, DG Premium,Esri World Imagery, Bing) 👇 
![i1](https://user-images.githubusercontent.com/1646072/41877913-b0922042-7898-11e8-98c2-4cb2f9882d97.png)

Verifying with another private source (Google) it is verified that they were added by local knowledge 👇 
![i2](https://user-images.githubusercontent.com/1646072/41877914-b0b5b8cc-7898-11e8-97d7-2cf4a1a6e7c2.png)
I am not making any modifications on these buildings.

🤔 any suggestions  @developmentseed/data-team?

**Comment by Rub21** [comment]
We did good work here, Closing this ticket!!
