### ISSUE TITLE
HOT Mapping and Validation: Typhoon Ompong: Cagayan and Batanes Structures

### ISSUE THREAD

**Issue by RichRico** [developmentseed/mapping#47]
This task is created to provide building footprints for Cagayan and Batanes.

Typhoon Ompong (Mangkhut) is projected to hit the northern areas of the Philippines, including Cagayan and Batanes. Mapping buildings is needed to augment the existing OSM layers.

Development Seed data team as part of the HOT community is taking part of this disaster mapping efforts, We are going to map and validate the buildings as the task describe!

### Tasking Manager 
- [ ] https://tasks.hotosm.org/project/5236

### Mapping sources

- Bing 
- tms[22]:https://{switch:a,b,c,d}.tiles.mapbox.com/v4/digitalglobe.0a8e44ba/{zoom}/{x}/{y}.png?

#### Task Coverage 
-  northern of Philippines

#### Activities
- Go through the instructions before you start. 
- Trace all the buildings you find in the task.

#### - Task #5236

![image](https://user-images.githubusercontent.com/8484029/45781181-e87ab300-bc24-11e8-83ee-28829ebf772c.png)

- Right now, the task is 77% mapped and 44% validated. So let's map and valid all the buildings at 100%.

![image](https://user-images.githubusercontent.com/8484029/45781223-ffb9a080-bc24-11e8-845c-cc0740c35b98.png)

If you have any comment or suggestion please post on this ticket!

cc. @olafveerman @Rub21 @developmentseed/data-team

**Comment by Rub21** [comment]
Closing this ticket, We are done here!
