### ISSUE TITLE
HOT Mapping: Tanzania missing buildings - Mbulu District

### ISSUE THREAD

**Issue by dannykath** [developmentseed/mapping#49]
As part of  geography awareness week  #OSMGeoWeek event , we will work on mapping buildings  in [Tanzania](https://tasks.hotosm.org/project/5428) 

> Tanzania has a very high incidence of Female Genital Mutilation, extreme poverty, early marriage and Gender Based Violence. NGOs on the ground need better maps to facilitate their outreach work and protect girls at risk of FGM.

Development Seed data team as part of the HOT community is taking part of mapping efforts, We are going to map buildings as the task describe!

### Tasking Manager 
- [ ] https://tasks.hotosm.org/project/5428

### Mapping sources

- Bing 
- Digital Globe
- ESRI Imagery

#### Task Coverage 
-  [Mbulu District](https://www.openstreetmap.org/#map=12/-3.9502/35.3109)

#### Activities
- Go through the instructions before you start. 
- Trace all the buildings you find in the task.

#### - Task #5428

![image](https://user-images.githubusercontent.com/8483644/48356865-34fecf80-e665-11e8-85c2-fba7e84d05a2.png)

- Right now, the task is 18% mapped and 2% validated. So let's map buildings.

If you have any comment or suggestion please post on this ticket!

cc. @developmentseed/data-team

**Comment by dannykath** [comment]
@developmentseed/data-team we will start working on this task on Wednesday at 4 pm.

**Comment by Rub21** [comment]
Closing this ticket!! this is done!
