### ISSUE TITLE
HOT mapping and validation: Help Venezuela 1: Barranquilla Buildings

### ISSUE THREAD

**Issue by RichRico** [developmentseed/mapping#50]
As the political situation in Venezuela continues to decline. HOT has Activated to help prepare for the influx of refugees into Colombia. Although this situation, and project, are urgent; this is very difficult mapping with no one immediately waiting on particular data. Please take your time, and care, that existing mapping is preserved while we improve the basemap of Barranquilla, Colombia.

This project is to use DigitalGlobe Premium imagery to fill in the structures of Barranguilla.

Development Seed data team as part of the HOT community is taking part of this disaster mapping efforts, We are going to map and validate the buildings as the task describe!

### Tasking Manager 
- [x] https://tasks.hotosm.org/project/5792

### Mapping sources
- DigitalGlobe Premium 

#### Task Coverage 
-  Barranquilla

#### Activities
- Go through the instructions before you start. 
- trace all the buildings you find in the task.

#### - Task #5792

![image](https://user-images.githubusercontent.com/8484029/54445014-f0b63580-4711-11e9-9a59-508f1d54ba3c.png)

- Right now, the task is 23% mapped and 19% validated. So let's map and valid all the buildings at 100%.

![image](https://user-images.githubusercontent.com/8484029/54445055-04fa3280-4712-11e9-995e-3c8820c580a3.png)

If you have any comment or suggestion please post on this ticket!

cc. @developmentseed/mapdata

**Comment by ediyes** [comment]
This task has already been completed. No more action.
