### ISSUE TITLE
HOT mapping and validation: Denizli Earthquake (M5.7) | 2019 Aug 8

### ISSUE THREAD

**Issue by RichRico** [developmentseed/mapping#52]
A series of earthquakes hit the Aegean region on August 8 2019 and a 5.7 magnitude earthquake hit the eastern parts of Denizli (Mecidiye-Bozkurt region) in mid-day. The magnitude was initially calculated as 6.5, then revised to 5.7.

Reports indicate low to moderate damage in buildings and low number of casualties in major settlements. Power grid is not functioning in rural regions and damage information on remote villages is yet to received as of the evening of the event.

Road network in the area is mostly digitized, however needing minor fixing. You can contribute to the missing roads task for the region [here](https://tasks.hotosm.org/project/4667)

Building data is mostly lacking in the region, and as HOT's local partner, Yer Çizenler is asking your help in contributing the OSM data in the region.

Development Seed data team as part of the HOT community is taking part of this disaster mapping efforts, We are going to map and validate the buildings as the task describe!

### Tasking Manager 
- [x] https://tasks.hotosm.org/project/6371

### Mapping sources
- `https://earthwatch.digitalglobe.com/earthservice/tmsaccess/tms/1.0.0/DigitalGlobe:ImageryTileService@EPSG:3857@jpg/{zoom}/{x}/{-y}.jpg?connectId=91e57457-aa2d-41ad-a42b-3b63a123f54a`

#### Task Coverage 
-  Denizli

#### Activities
- Go through the instructions before you start. 
- trace all the buildings you find in the task.

#### - Task #6371

![image](https://user-images.githubusercontent.com/8484029/62881177-ca161e00-bcf4-11e9-996e-370dc3002d97.png)

- Right now, the task is 19% mapped and 1% validated. So let's map and valid all the buildings at 100%.

![image](https://user-images.githubusercontent.com/8484029/62881362-47da2980-bcf5-11e9-8f05-499028d2bd7a.png)

If you have any comment or suggestion please post on this ticket!

cc. @developmentseed/mapdata

**Comment by ediyes** [comment]
no more action here.
