### ISSUE TITLE
HOT validation: In response Mayon Volcano Eruption

### ISSUE THREAD

**Issue by piligab** [developmentseed/mapping#7]
Mayon Volcano continue to be restive, spewing steam, ash and with lava flows beginning 14th January, 2018. As of 22nd January, the government has raised the warning to Alert Level 4 of 5 (Hazardous Eruption Imminent) 

Development Seed data team as part of the HOT community is taking part of this disaster mapping efforts, We are going to validate the buildings and highways as the task describe!

### Tasking Manager 
- [x] https://tasks.hotosm.org/project/4037

### Mapping sources
- Bing, Digital Globe, ESRI, and Mapbox.
- JOSM 

#### Task Coverage 
-  In the province of Albay in Bicol Region, on the large island of Luzon in the Philippines.

#### Activities
- Go through the instructions before you start. 
- Valid all the settlements, building, highway, waterway in the task.

#### - Task #4037
![image](https://user-images.githubusercontent.com/19536044/35232622-f3d7196e-ff69-11e7-8691-4c07d2bc7fa7.png)

- Right now, the task is 47% mapped and 2% validated. 
![image](https://user-images.githubusercontent.com/19536044/35352358-aef48878-0111-11e8-8308-573cc85645d1.png)

### So let's valid all the priority area to 100%. 

If you have any comment or suggestion please post on this ticket!

cc. @olafveerman @Rub21 @developmentseed/data-team

**Comment by geohacker** [comment]
Thank you @piligab!

cc @govvin - our team in Peru is going to help bring priority area validation to 100%.

**Comment by govvin** [comment]
This is awesome, @piligab ! Thank you.

Thanks for the heads-up @geohacker .

**Comment by piligab** [comment]
:wave: @geohacker, @govvin yesterday we finished validate the priority area to :100:% . :rocket: 

![image](https://user-images.githubusercontent.com/19536044/35351688-a819103e-010f-11e8-9424-62758b75d3c7.png)
  
Also we finished to map and validate all task to :100:% . 
:clap: Good work @developmentseed/data-team. :tada: 

![image](https://user-images.githubusercontent.com/19536044/35352200-37a3e340-0111-11e8-9379-814f9b3ddf35.png)
 
cc. @Rub21

**Comment by govvin** [comment]
Thank you very much @developmentseed/data-team

You did a great job!

**Comment by olafveerman** [comment]
That is great, fantastic @developmentseed/data-team !
